### ISSUE TITLE
keep cursor in chat after message

### ISSUE THREAD

**Issue by bhaktatejas922** [autoinfra-ai/lingtual-embedded-chat#1]

**Comment by deveshXm** [comment]
Hey. !'d like to work on this.

**Comment by bhaktatejas922** [comment]
Awesome! Let me know if you need anything or have any questions :)

**Comment by deveshXm** [comment]
1. Could you please assign this issue to me. 
2. Can I get a brief description of the issue.
3. Is this chatbot using openAI or any other model ? If yest, how can I integrate the API?

**Comment by deveshXm** [comment]
Hi. I suppose in this issue you meant whenever enter is pressed after typing something the focus from from the Input Element is removed. I have fixed that. Kindly assign me so I can create a PR.
